server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  resources:
    static-locations: /resources/static/logo.jpg
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: php4koPkHcap13jQ246bBbyxEFVZFCW6
            client-secret: qjfXit-LuG9uVKxYfz0fJLDHr6m1hZjSvv4rHcrFIxdztskgk9rcPbsGWYAtDnK9
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-8pf64q4c.us.auth0.com/
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    table: z_schema_version
    placeholder-replacement: false
  datasource:
    password: seaftajobs
    url: jdbc:postgresql://localhost:5432/seaftajobsdb
    username: seaftajobs
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
